# Page settings

baseURL = "https://cv.felixdubrownik.de/"
languageCode = "en"
title = "Felix Dubrownik - CV"
#theme = "hugo-devresume-theme"
#googleAnalytics = "UA-XXXXXXX-Y"

[params]
    author = "Felix Dubrownik"
    description = "Felix Dubrownik - Senior Software Engineer CV"

    primaryColor = "#407fb9"
    textPrimaryColor = "#292929"

    [params.profile]
        enable = true
        name = "Felix Dubrownik"
        tagline = "Senior Software Engineer"
        avatar = "portrait256.png"

    [params.contact]
        enable = true
        location = "Kiel / Hamburg, Germany"

#         [[params.contact.list]]
#         icon = "fas fa-phone-square"
#         url = "tel:#"
#         text = "0123 4567 890"
        [[params.contact.list]]
        icon = "fas fa-envelope-square"
        url = "mailto:fdubrownik+cv@gmail.com"
        text = "fdubrownik+cv@gmail.com"
        [[params.contact.list]]
        icon = "fas fa-globe"
        url = "#"
        text = "cv.felixdubrownik.de"

    [params.skills]
        enable = true

        [[params.skills.list]]
        title = "Technical"
        [[params.skills.list.items]]
        details = "Golang"
        [[params.skills.list.items]]
        details = "Rust"
        [[params.skills.list.items]]
        details = "Kubernetes"
        [[params.skills.list.items]]
        details = "Cloud Infrastructure"
        [[params.skills.list.items]]
        details = "Lead and deliver complex software systems"
        [[params.skills.list.items]]
        details = "C++"


        [[params.skills.list]]
        title = "Professional"
        [[params.skills.list.items]]
        details = "Effective communication"
        [[params.skills.list.items]]
        details = "Team player"
        [[params.skills.list.items]]
        details = "Strong problem solver"

    [params.education]
        enable = true

        [[params.education.list]]
        degree = "BSc in Computer Science"
        university = "Christian-Albrechts-Universität Kiel"
        dates = "2008 - 2012"

    [params.awards]
        enable = true

        [[params.awards.list]]
        name = "Koordinaten Festival für räumliche Medien - FH Kiel"
        body = "3rd place and audience award - [vimeo](https://vimeo.com/120791544)"
        date = "2014"

    [params.languages]
        enable = true

        [[params.languages.list]]
        name = "German"
        level = "Native"
        [[params.languages.list]]
        name = "English"
        level = "Professional"

    [params.interests]
        enable = true

        [[params.interests.list]]
        name = "Climbing"
        [[params.interests.list]]
        name = "Photography"
        [[params.interests.list]]
        name = "Travelling"
        [[params.interests.list]]
        name = "Woodworking"

    [params.summary]
        enable = true
        text = """I am an experienced Software Engineer with a broad knowledge of application and infrastructure architecture.

Having spent all of my professional career in start-ups I see myself as a generalist with an agile mindset and a hands-on mentality.

        """

    [params.experience]
        enable = true

        [[params.experience.list]]
        title = "Senior Software Engineer - Technical Lead"
        dates = "2019 - Present"
        company = "Hanko GmbH"
        details = "[Hanko](https://hanko.io) offers a SaaS for Passwordless Authentication and Identity based on FIDO2. "
        [[params.experience.list.items]]
        details = "Hanko Authentication API - Golang based FIDO Authentication Server"
        [[params.experience.list.items]]
        details = "Hanko Identity - Full fledged Identity solution with Authentication, Identity Management, Authorization and OIDC connection."
        [[params.experience.list.items]]
        details = "Kubernetes Infrastructure running on AWS and mangaged with kops"
        [[params.experience.list.items]]
        details = "Hanko Operator - Using the Kubernetes Operator Framework to manage the SaaS Products and let clients spawn instances via a web-console"

        [[params.experience.list]]
        title = "Lead Software Developer"
        dates = "2015 - 2019"
        company = "li - Light Instruments GmbH"
        details = "At [li - light instruments GmbH](https://light-instruments.de/) we developed a Hardware/Software combination that enhanced beamers with the capabilities of video mapping. In addition we implemented a Content Management System to schedule Images and Videos in a Digital Signage context. As the first employee I was lucky to be part of the creation of this company from the beginning and implemented a very broad set of functionalities. Including but not limited to:"
        [[params.experience.list.items]]
        details = "C++ graphics core utilizing OpenGL and GStreamer"
        [[params.experience.list.items]]
        details = "Golang server for scene and video configuration from IPad App and CMS"
        [[params.experience.list.items]]
        details = "CMS Golang Server and AWS server infrastucture with Ansible"
        [[params.experience.list.items]]
        details = "Configuring custom Linux and provisionig toolkit"
        [[params.experience.list.items]]
        details = "Incremental over-the-air update mechanism with multi version boot and rollback mechanism"

        [[params.experience.list]]
        title = "Research Assistant - Software Challenge"
        dates = "2011 - 2014"
        company = "Christian Albrechts Universität Kiel - Department of Technical Computer Science"
        details = "The [Software Challenge](https://software-challenge.de/) is an annual programming competition in which students write a player for a yearly changing board game. Their programs compete against each other and the winners are awarded a scholarship for studying computer science. I implemented the server side mechanics for a game and assisted teachers in schools to train the fundamentals of programming in Java."

        [[params.experience.list]]
        title = "Research Assistant - Exercise Group Leader Digital Systems"
        dates = "2009 - 2010"
        company = "Christian Albrechts Universität Kiel - Department of Technical Computer Science"
        details = "In my third semester I started as an exercise group leader for the course Digital Systems. Teaching first semester students the fundamtentals of computer architecture based on digital circuits, memory and automata."

    [params.projects]
        enable = false

        [[params.projects.list]]
        title = "Project Lorem Ipsum"
        meta = "Open Source"
        tagline = "You can use this section for your side projects. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus."

    [params.information]
        enable = false

        [[params.information.list]]
        title = "Papers"
        [[params.information.list.items]]
        details = "2018 · Lorem Ipsum"
        [[params.information.list.items]]
        details = "2016 · Sed Fringilla"

        [[params.information.list]]
        title = "Interests"
        details = "Climbing, Snowboarding, Photography, Travelling"

    [params.social]
        enable = true

        [[params.social.list]]
        icon = "fab fa-github-square"
        url = "//github.com/aspeterakete"
        title = "aspeterakete"
        [[params.social.list]]
        icon = "fab fa-linkedin"
        url = "//linkedin.com/in/felix-dubrownik-32996b1bb"
        title = "felix-dubrownik"
        [[params.social.list]]
        icon = "fab fa-twitter-square"
        url = "//twitter.com/aspeterakete"
        title = "@aspeterakete"
        [[params.social.list]]
        icon = "fab fa-xing-square"
        url = "//xing.com/profile/Felix_Dubrownik/cv"
        title = "Felix_Dubrownik"






